<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Threading.AccessControl" Version="8.0.0" />
    <ProjectReference Include="..\WireguardSplitTunnel.Core\WireguardSplitTunnel.Core.csproj" />
  </ItemGroup>
</Project>
