<Project>
  <PropertyGroup>
    <VersionPrefix>0.2.2</VersionPrefix>
    <MinimumAutoUpdateVersion>0.2.0</MinimumAutoUpdateVersion>
    <RollbackCompatibleFromVersion>0.2.0</RollbackCompatibleFromVersion>
    <StateSchemaVersion>1</StateSchemaVersion>
    <Version>$(VersionPrefix)</Version>
    <AssemblyVersion>$(VersionPrefix).0</AssemblyVersion>
    <FileVersion>$(VersionPrefix).0</FileVersion>
    <InformationalVersion>$(VersionPrefix)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
